name: Deploy Website via SSH

on:
  push:
    branches:
      - main  # Adjust to your desired branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Create SSH directory and known_hosts file
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H 52.77.254.127 >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts  # Ensure the permissions are set correctly

    - name: Copy Files to Server (Skip Host Key Checking)
      run: |
        scp -o StrictHostKeyChecking=no -r ./Devops-HTML/* ubuntu@52.77.254.127:/www/wwwroot/CHAMAXX.LINKPC.NET
      env:
        SSH_AUTH_SOCK: /tmp/ssh-agent.sock
